volumes:
  node-data: {}
  postgres_data: {}

services:
  postgres:
    image: postgres:latest
    container_name: auto_drive_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - infrastructure
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      RPC_ENDPOINT: ${RPC_ENDPOINT}
      PRIVATE_KEYS_PATH: ${PRIVATE_KEYS_PATH}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      OBJECT_MAPPING_ARCHIVER_URL: ${OBJECT_MAPPING_ARCHIVER_URL}
      MAX_CACHE_SIZE: ${MAX_CACHE_SIZE}
      JWT_SECRET: ${JWT_SECRET}
      FILES_GATEWAY_URL: ${FILES_GATEWAY_URL}
      FILES_GATEWAY_TOKEN: ${FILES_GATEWAY_TOKEN}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      AUTH_SERVICE_API_KEY: ${AUTH_SERVICE_API_KEY}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "${PORT}:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 20s
      timeout: 2s
      retries: 3
    profiles:
      - backend
  hasura:
    image: hasura/graphql-engine:v2.40.0.cli-migrations-v3
    volumes:
      - ./hasura:/app
    restart: unless-stopped
    environment:
      # Essential Environment Variables
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET} # Admin access secret
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET} # JWT authentication secret

      # Console and Development Mode
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE} # Disable console in production
      HASURA_GRAPHQL_DEV_MODE: "true" # Disable development mode features

      # Role and CORS Settings
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous # Default role for unauthenticated users
      HASURA_GRAPHQL_CORS_DOMAIN: ${HASURA_GRAPHQL_CORS_DOMAIN} # Allowed domains for CORS
      HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: "true"

      # Performance and Connection Settings
      HASURA_GRAPHQL_MAX_CONNECTIONS: 100 # Maximum number of database connections
      HASURA_GRAPHQL_STRIPES: 2 # Number of connection pool stripes
      HASURA_GRAPHQL_CONNECTIONS_PER_STRIPE: 50 # Connections per stripe
      HASURA_GRAPHQL_IDLE_TIMEOUT: 180 # Idle connection timeout in seconds
      HASURA_GRAPHQL_TIMEOUT: 60 # Request timeout in seconds

      # Logging Settings
      HASURA_GRAPHQL_LOG_LEVEL: "warn" # Log verbosity level
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup,http-log,webhook-log,websocket-log,query-log" # Enabled log types

      # Security and Authorization
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "false" # Disable query allowlisting

    ports:
      - "${HASURA_GRAPHQL_PORT}:8080"
    command:
      - graphql-engine
      - serve
    profiles:
      - infrastructure
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - infrastructure
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${AUTH_PORT}:3030"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - AUTH_PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SECRET_ALGORITHM=${JWT_SECRET_ALGORITHM}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - API_SECRET=${API_SECRET}
    profiles:
      - auth
