---
- name: Pull new image, update ssecret, and reboot
  hosts: "{{ target_machines }}"
  vars:
    env_file_path: ~/deploy/auto-drive/.env
  tasks:
    - name: Show current host information
      ansible.builtin.debug:
        msg: |
          Current target machines: {{ target_machines }}
          Current inventory hostname: {{ inventory_hostname }}
          Current system hostname: {{ ansible_hostname }}
          Current connection host: {{ ansible_host }}

    - name: Set matched group name for this host
      ansible.builtin.set_fact:
        matched_group: "{{ group_names | select('match', target_machines ) | first | default('undefined') }}"

    - name: Import environment variables from file
      ansible.builtin.include_vars:
        file: environment.yaml
      ignore_errors: yes

    - name: Validate required variables
      ansible.builtin.fail:
        msg: "Missing required variable: {{ item }}"
      when: vars[item] is undefined or vars[item] == ''
      loop:
        - infisical_client_id
        - infisical_token
        - infisical_project_id

    - name: Login to Infisical and get access token
      ansible.builtin.shell: >
        infisical login \
          --method=universal-auth \
          --client-id={{ infisical_client_id }} \
          --client-secret={{ infisical_token }} \
          --plain
      register: login_cmd

    - name: Update image to backend container key BACKEND_IMAGE in folder '/{{ matched_group }}' image to {{ image_tag }}
      ansible.builtin.shell: |
        infisical secrets --projectId {{ infisical_project_id }} --path /{{ matched_group }} --env prod --token {{ login_cmd.stdout }} set BACKEND_IMAGE={{ image_tag }}
      when: image_tag is defined and image_tag != ''
      register: hello_output

    - name: Update .env
      ansible.builtin.shell: |
        env_file=$(infisical export --projectId {{ infisical_project_id }} --path /{{ matched_group }} --env prod --token {{ login_cmd.stdout }})
        # Create all necessary directories
        mkdir -p ~/env-archives
        timestamp=$(date +%s)
        # Only try to backup existing .env if it exists
        if [ -f {{ env_file_path }} ]; then
          cat {{ env_file_path }} > "$HOME/env-archives/{{ ansible_hostname }}.${timestamp}.txt"
        fi
        echo "$env_file" > $HOME/deploy/auto-drive/.env
      register: env_output

    - name: Launch docker compose
      ansible.builtin.shell: |
        /usr/bin/docker compose --env-file {{ env_file_path }} -f ~/deploy/auto-drive/docker-compose.prod.yml up -d --remove-orphans

    - name: Show env output
      ansible.builtin.debug:
        var: env_output.stderr
