---
- name: Setup infisical
  hosts: "{{ target_machines }}"
  become: true
  tasks:
    - name: Install infisical
      ansible.builtin.shell: |
        infisical -v
        if [ $? -ne 0 ]; then
          curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical
        fi
      register: hello_output
