name: Services

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Only trigger on changes within auth or backend
      - "auth/**"
      - ".github/**"
  pull_request:
    paths:
      - "backend/**" # Only trigger on changes within auth or backend
      - "auth/**"
      - ".github/**"
  workflow_dispatch:

env:
  NEXT_PUBLIC_PROJECT_ID: "mocked-value-for-CI/CD"

jobs:
  backend-build-check:
    name: Services Build, Test and Lint Check
    runs-on: ubuntu-latest

    # Cache dependencies to speed up the workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Yarn
        run: corepack enable

      - name: Build submodules
        run: make -B submodules

      - name: Install dependencies
        run: corepack use yarn@4.2.2

      - name: Build all services
        run: make -B all

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
